schema_version = "1.0.0"

id = "kitsune_tools"
name = "Kitsune Tools"
version = "1.0.0"
tagline = "Set of tools for Blender that can be useful for assisting on character rigging. Previously embedded within KitsuneSourceTool"
maintainer = "Toppi"
type = "add-on"

blender_version_min = "4.5.0"

license = ["SPDX:GPL-3.0-or-later"]
